### ISSUE TITLE
Unable to access server with usb2lan adapter, error code 50221

### ISSUE THREAD

**Issue by tatsunoko** [polaris-/dwc_network_server_emulator#34]
I can access the server and play TvC using built in wifi. 

When I switch the default connection to my usb port that uses a nintendo lan adapter, i receive error code 50221.

Net play is faster and more stable with these adapters.
![dongle](https://cloud.githubusercontent.com/assets/7709546/3212708/bcc96cce-ef6e-11e3-9ee1-4397fded0a20.jpg)

**Comment by tatsunoko** [comment]
We discussed this on another forum, I have asked SMT-DDR to continue here. This is what he posted:
SMTDDR-
omg, yea... I cannot get it to work with my USBLAN adapter either. Wired connections apparently don't work with OfflineNetworkEnabler which is lame to the extreme. I do play with a wired connection, but that's because I can alter my network during the connection-test and make it pass even though it's pointing to the polaris server. Then I use my own custom Riivolution patch to start TvC.

For you guys who want to do wired, you should probably first set everything up normally in the connection settings... then just before going online with TvC, change the DNS in your home routers. Please note that this means all the DNS lookups in your home go to the polaris server so in theory they'd know all the websites anyone on that router visits.

If you're willing to do this, I should probably upload my riivolution patch for TvC to disable SSL so you can go online.

EDIT: ....but.... the problem with this... is that it's not legal to distribute the patched file.... so... while I can upload the riivolution patch files, you'll need to go find main.dol for TvC yourselves. I'm sure I can write a program to patch the main.dol myself and upload that. You just need to find main.dol. I will tell you that if you... um...somehow... have the ISO image of TvC on your computer, the file "main.dol" is in there. That is all.

**Comment by SMTDDR** [comment]
The reason OfflineNetworkEnabler is needed is because polaris-server won't pass the connection test. Later on I will upload a pcap file of a successful connection test, perhaps polaris server can emulate it. I don't recall seeing any SSL stuff. I do remember seeing the 3 natneg servers. If the polaris server could pass the connection test, then the only thing needed is my custom Riivolution patch for TvC. It doesn't do anything spectacular, simply edit's main.dol to remove the "s" from "https" for the url "https://naswii.nintendowifi.net". That's the only SSL in the whole game. That edit + polaris DNS = game on.

EDIT: Now that I think about it.... this issue is probably meant for OfflineNetworkEnabler and/or brainslug. I don't think it's a bug that can be fixed by polaris. The one thing polaris might be able to do is the emulation of a successful connection test.

**Comment by AdmiralCurtiss** [comment]
Not a problem with this server, poke the offline network enabler dev(s).

**Comment by tatsunoko** [comment]
The "allow wii to pass connection test" fix seems to have eliminated the need for offline network enabler. It also allowed my usb2lan connection to work.

**Comment by SMTDDR** [comment]
Right, that's why getting it fixed was pursued. Then the provided  Riivolution patch was all that was needed.

http://www.gamefaqs.com/boards/953921-tatsunoko-vs-capcom-ultimate-all-stars/69443739

The Riivolution patch is pretty generic and I expect it to work for most games. Or at the minimum, other people can build on my example for any other URLs using SSL in any game.
