### ISSUE TITLE
Bypass HTTPS code is incorrect

### ISSUE THREAD

**Issue by Maganet** [polaris-/dwc_network_server_emulator#72]
I have an incorrect code for my Pokemon Platinum. When I use the WfcReplay and a Platinum rom, it gives me an CPUE code, but my cartridge is CPUP. Does the code has to be CPUP or will CPUE work?
Thank you.

**Comment by AdmiralCurtiss** [comment]
WfcReplay issues have nothing to do with the server, report over there: https://github.com/Prof9/wfcreplay

Also, to get a working code you have to use a ROM that exactly matches your game card. You should dump your own game instead of guessing what version and revision it is and matching it to a downloaded copy.

**Comment by mm201** [comment]
FWIW, if you can dump your ROM, you can probably also run a NoSSL patch.
