### ISSUE TITLE
is the server still up ? (for Pokemon White 2)

### ISSUE THREAD

**Issue by shadowblak** [polaris-/dwc_network_server_emulator#80]
I have done everything & this is my first time so I never connect to this server before.I still keep getting error code 20100 & I use Desmume 0.9.7 wifi. So I just want to know is the server still up or not. Thank you !

**Comment by JzargoTheMage** [comment]
Quite a few people seem to be having issues with connecting to the server. There's a few things it could be. First, make sure you have Desmume completely set up (there were a lot more steps than I expected when I tried, so you may be experiencing the same issue) and that your firewall isn't blocking it. Also, there is every chance that the server is down right now (it isn't guaranteed to be online 24/7 since it is in development) or that it just isn't compatible with the game. Yes, there were videos posted of users connecting and doing things, but a more recent update may have changed something essential to certain games. We just have to wait for it to be updated or brought back online. Pro tip: don't worry about it. It isn't dead. I'm going to leave things at that.

**Comment by shadowblak** [comment]
I see.. , Thanks for your answers !

**Comment by JzargoTheMage** [comment]
Could you please close this issue now? I don't have the power to, even though I answered your question. It would make it easier for the coders to find actual issues if the list was cleaned up a bit. Thank you in advance

**Comment by polaris-** [comment]
Alright, closing.
