### ISSUE TITLE
Pokémon Dream World (BW/BW2)

### ISSUE THREAD

**Issue by RicoSantos** [polaris-/dwc_network_server_emulator#85]
Is it possible to be "recreated"? (I guess not but doesn't hurt to ask.) I don't know how far programming can go.

**Comment by mm201** [comment]
Pokémon-specific servers are outside the scope of this project, but please see:

https://github.com/mm201/pkmnFoundations/issues/8

**Comment by polaris-** [comment]
Closing because this should be on the pkmnFoundations issue tracker as mm201 pointed out: https://github.com/mm201/pkmnFoundations/issues

That said, I've done some work involved in the Dream World stuff but it's up to mm201 to implement it as pointed out in the linked ticket. It will work in time, but I can't say when or how exactly it'll work.
