### ISSUE TITLE
My server broke.....AGAIN.....

### ISSUE THREAD

**Issue by kyle95wm** [polaris-/dwc_network_server_emulator#93]
Okay so this has been the hundredth time the server decided to break meaning it wouldn't allow connection tests to succeed. I started getting complaints 2 hours ago about the problem and can't find a solution

Ive tried restarting the server several times, resetting IPtables, all the works and can't get the damn thing back in business

What the hell do I do???

@SMTDDR I'd really appreciate any help you can give me. Ive tried that command you mentioned "curl" and it worked but for SOME reason the Wii just can't connect. Dolphin works fine but the Wii isn't connecting. It just vies one HTTP get request and thats when the error kicks in

**Comment by SMTDDR** [comment]
So with the threaded mod on your nas_server.py, you still get complaints but...
- curl -v your_IP -H 'Host: conntest.nintendowifi.net   ....still works?
- Dolphin keeps working too? 
- Only the Wii has the problem?

Sounds like altwfc is working and the problem is somewhere between the Wii & altwfc.  Is the Wii on the same router as your altwfc? What game are you playing? How is that game patched to use altwfc? Next time this happens can you, in addition to the curl command, test your DNS server with: <code> dig @yourIPaddr conntest.nintendowifi.net </code> and <code> dig@yourIPaddress naswii.nintendowifi.net </code>. If those work, then I have to believe the server is getting DDoSed since the interwebz are very hostile. Dolphin working because your PC probably has DNS lookups cached, but the Wii tends to forget pretty fast and does them again regularly afaict.

**Comment by kyle95wm** [comment]
Yes the Wii is on the same network (using a wired connection) I mostly play Mario Kart Wii and how they're patched is with the NoSSL  code

I've tried both commands and got the following output

Kyle-iMac:~ kyle$ dig @99.238.209.85 conntest.nintendowifi.net

; <<>> DiG 9.8.3-P1 <<>> @99.238.209.85 conntest.nintendowifi.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40400
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;conntest.nintendowifi.net. IN  A

;; ANSWER SECTION:
conntest.nintendowifi.net. 0    IN  A   99.238.209.85

;; Query time: 1 msec
;; SERVER: 99.238.209.85#53(99.238.209.85)
;; WHEN: Mon Dec 29 16:06:52 2014
;; MSG SIZE  rcvd: 59

Kyle-iMac:~ kyle$ dig @99.238.209.85 naswii.nintendowifi.net

; <<>> DiG 9.8.3-P1 <<>> @99.238.209.85 naswii.nintendowifi.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61643
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;naswii.nintendowifi.net.   IN  A

;; ANSWER SECTION:
naswii.nintendowifi.net. 0  IN  A   99.238.209.85

;; Query time: 42 msec
;; SERVER: 99.238.209.85#53(99.238.209.85)
;; WHEN: Mon Dec 29 16:

However since those appear to be working, the internet icon on the HBC refuses to light up as it should be while using my server connection. Other times it's able to connect to the internet when not using my DNS

The connection tests also continue failing. This happened last time on my Kali VM so I switched to Ubuntu and installed everything that was required and it began working again but now Im in the same situation as before.

Ive made sure I routed my port 8080 to port 80 (but I still run as root anyway) so this shouldn't have made a difference.

Its frustrating me that I can't fix the problem as easily as I did before

**Comment by SMTDDR** [comment]
Hmm... HBC, you're not using this are you? http://wiibrew.org/wiki/Offline_Network_Enabler
That thing has problems and can screw up connection profiles entirely.

**Comment by kyle95wm** [comment]
Actually I do use that to quickly switch connections. Matters aside, not one single connection test from the Wii is getting through. Ive tried switching to my wireless card on my Wii and still it won't work I don't understand whats going on or why this is happening

**Comment by SMTDDR** [comment]
I am putting the blame squarely on OfflineNetworkEnabler. That thing wrecked my Wii's connection settings too.  You should stop using it. I know it's painfully slow to use the Wii's menu system, but really... O.N.E. just causes the problems you're seeing now.

**Comment by kyle95wm** [comment]
Already have and tried clearing all connections and keep getting error 52221 with
192.168.101.100 - - [29/Dec/2014 16:31:40] "GET / HTTP/1.1" 200 -
on the console - not the usual "availability request" stuff

This isn't just happening to me its happening to TONS of other people

**Comment by SMTDDR** [comment]
ok, to IRC

**Comment by SMTDDR** [comment]
This issue can probably be clsoed now, but for the sake completeness the issue was apparently during the Wii's conntest.nintendowifi.net call for connection testing. While it seems that the Wii only cares that it gets HTTP 200 OK back, the connection test will fail if the response body is too big. The problem was fixed when the following was added:

```
if self.headers['Host'] == 'conntest.nintendowifi.net':
       self.wfile.write("ok")
else:
       self.wfile.write(variable_containing_huge_html_custom_homepage_that_breaks_wii)
```
